logo = "images/lomond-logo.png"
home = "Home"
menufixed = true
 
[hero]
enable = true
heading = "Automation and Robotics for Real‑World Operations"
description = "We design and deploy reliable robotic and automation systems for labs and factories."
videoThumb = "images/overview.png" # ensure this file exists at static/images/overview.png
videoURL = ""
btnText = "Contact"
btnURL = "/contact/"

footerDescription = "Integer posuere erat a ante venenati dapibus posuere velit aliquet. Fusce dapibus, tellus cursus commodo, tortor mauris sed posuere."
footerServiceTitle = "Service"
footerQuicklinkTitle = "Quicklinks"
footerAboutTitle = "About"
footerSubscribeTitle = "Subscribe"

[subscription]
enable = false
mailchimp_form_action = ""
mailchimp_form_name = ""


